### ISSUE TITLE
Use GitHub issue tracker for goals/milestones

### ISSUE THREAD

**Issue by gitjuba** [gitjuba/javascript-platformer#14]
Or perhaps use issues distributed into projects. Anyways, move them away from the README.

- [x] Move Gameplay goal I
- [x] Outline Gameplay goal II
- [x] Organize rest of issues into gameplay related and other issues

**Comment by gitjuba** [comment]
I won't plan too far ahead. Consider this done.
